# Generated by Django 5.2.4 on 2025-07-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
