# Generated by Django 5.2.4 on 2025-07-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_rename_updated_blog_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="twitter",
            new_name="github",
        ),
    ]
